### ISSUE TITLE
Buen proyecto!

### ISSUE THREAD

**Issue by BSG-Walter** [NickCis/among-us-proxy#1]
estaba por escribir en ingles pero veo que sos de buenos aires, me ahorraste el comerme la cabeza jaja. no tenes pensado agregar la opcion de que los host puedan hacer publicas sus salas? que el mismo programa tenga su propia lista de servidores que puedan elegir.

**Comment by NickCis** [comment]
Jajajaja, si, esta todo en inglés por costumbre (pero bueno, las capturas del juego tmb me delataban).

Siendote sincero no pensé la idea. Siempre jugué con amigos, así que, nunca tuve en la cabeza la posibilidad de tener que buscar una sala.

No sería algo complejo, pero habría que montar algún especie de servicio (seguro con la parte free de firebase debería alcanzar).

Si tenes alguna idea en la cabeza, lo podemos hablar y lo vamos viendo. Vos sabes Nodejs / Typescript como para colaborar?

**Comment by BSG-Walter** [comment]
No, no se nada de eso. apenas estoy aprendiendo lo basico de C. yo lo que queria hacer por mi cuenta era usar este otro proxy y crearle una lista de servidores https://github.com/Tudor3510/Proxom

Lo que tenia en mente era montar un servidor web, armar una bd mysql y meterle archivos php para agregar/quitar los servidores a la bd, asi no tengo que meter las credenciales de mysql en el propio programa. Pero ya te digo soy muy novato en esto y seguramente hubiera hecho algo que seria un desastre en seguridad y en todo.

**Comment by NickCis** [comment]
No conocía ese [Proxom](https://github.com/Tudor3510/Proxom) y eso que busqué en github para ver si había algo hecho. Pero bueno, por lo que vi de ese Readme no parce muy amigable :rofl: 

Me parece que lo más sencillo va a ser crear una instancia de firebase para usar firestore (una base de datos que esta pensada para apps), así ni hay que hacer backend y que la primera iteración sea sencillamente una lista de partidas. Y queres ir probando cosas con react + firebase, podes ponerte a jugar un poco. La aplicación esta hecha en electron (que básicamente es un chrome empaquetado), así que es meter código como si fuera web.

Ahora estoy cambiando un par de cosas en el stack de red de este proxy (usa un servicio llamado ngrok para que el host exponga el puerto) y quería cambiarlo por WebRTC (así es más p2p).
