### ISSUE TITLE
Can't execute make script

### ISSUE THREAD

**Issue by tahelmo** [NickCis/among-us-proxy#2]
Hello, I tried opening your project in developement mode, but failed at the last step when I tried to execute to run `npm run lerna -- make` 
![image](https://user-images.githubusercontent.com/43392443/94330756-50db9800-ff95-11ea-8001-982af21513f2.png)

**Comment by NickCis** [comment]
Hi, it's a typo, it should be `npm run lerna -- run make`. The `gui` and `among-us-proxy` packages have a `make` script that build the distributable package.

**Comment by tahelmo** [comment]
Thank you for your quick reply. I tried adding run before but it is giving me this error instead.
![image](https://user-images.githubusercontent.com/43392443/94331732-08c07380-ff9d-11ea-928e-cf9d16e6acab.png)
Did you try this command on the latest source code version?

**Comment by NickCis** [comment]
Mmm, that's quite strange. Haven't you modified the file : `packages/among-us/packge.json` ?.

Please post that file and the output of the following commands:
- `npm --version`
- `node --version`.

In what operative system are you running this?. (Is is Linux?).

**Comment by tahelmo** [comment]
Yes I am using linux.

**Comment by NickCis** [comment]
Please provide the requested information, so I can try to help you.

**Comment by tahelmo** [comment]
Sure I'll do once I got my hands on my laptop, thank you for your quick answers.

**Comment by tahelmo** [comment]
Hello, 
on `npm --version`, the output is: `6.14.8`
on `node --version`, the output is: `v10.15.2`

**Comment by NickCis** [comment]
Can you post the `packages/among-us-proxy/packge.json` file?. It should be the same as [this one](https://github.com/NickCis/among-us-proxy/blob/master/packages/among-us-proxy/package.json).

The error that you've posted says that the `package.json` isn't a valid json file. Perhaps, you've accidentally modified that file. Could it be that?
