### ISSUE TITLE
Mobile Proxying.

### ISSUE THREAD

**Issue by roobscoob** [NickCis/among-us-proxy#6]
Is there a way to proxy a mobile connection? When running the GUI, it only shows up on localhost, not other devices connected to the network. Is there a way to implement this?

**Comment by NickCis** [comment]
Hi there!,

Yes, It should be rather simple. Current implementation only sends the discovery package to the local machine, but, broadcasting to the local network is not a hard task. I'll implement it and ping you back.

Just a few questions:
- Will you only use your mobile phone to connect to a game?, If so, why aren't you using the desktop client instead?.
- Are you planning to connect more than one mobile device to the same proxy client (that runs on a PC)?
- Are you also planing to host a game on a mobile phone and use the proxy (running in a computer) to play with your friends?.

**Comment by roobscoob** [comment]
1. I don't understand this question? Sorry. Would you mind rephrasing?
2. It would be preferable, though not necessary
3. It would be preferable, though not necessary

**Comment by NickCis** [comment]
1. If you are using a computer to run the proxy, why are you playing the game on mobile instead of using the pc to play it?. (It's just out curiosity, if you don't what to give an answer just ignore it, no problem!)

**Comment by pepijnmm** [comment]
@NickCis mobile among us is free so I think a lot of people will start of or just stay at mobile if they don't have a problem with the control. Where as on steam it costs 4 dollar.

**Comment by NickCis** [comment]
I've just uploadede a fix that will allow guests from the local network. If you know how to use the proxy from the source give it a try, if not, i'll further test it an upload a new version in the following days.

**Comment by Droid-MAX** [comment]
recommand use p2p to connect the game, like n2n or openvpn, and udp_relay tools to forward broadcast packets. 
https://github.com/thomseddon/udp-replicator

**Comment by Droid-MAX** [comment]
Can someone come and test the p2p connection of among us on the Android platform? I just compiled udp-replicator.
https://github.com/Droid-MAX/udp-replicator/releases/tag/1.0

**Comment by NickCis** [comment]
@Droid-MAX That UDP replicator project does the same than this among-us-proxy. This project was built specifically to play among us, so you shouldn't do any of the setup there. If you read the main readme of this repo, you'll probably understand that both projects are doing the same.

**Comment by NickCis** [comment]
This can be done in [`1.2.0`](https://github.com/NickCis/among-us-proxy/releases/tag/v1.2.0)
