### ISSUE TITLE
Bypass ngrok

### ISSUE THREAD

**Issue by SirDMZ** [NickCis/among-us-proxy#7]
Hello Nick,

It would be cool for those of us who are comfortable with port forwarding to be able to bypass ngrok and just do this directly.

**Comment by NickCis** [comment]
Hi there!.

The next version will allow to disable the creation of ngrok redirection (if you want, you can try it out building from source. I'll release the version after I have some time to test it).

Anyway, the port used is `8080`, so if you expose that port from the host others will be able to connect to it :)

**Comment by NickCis** [comment]
This can be done on [`1.2.0`](https://github.com/NickCis/among-us-proxy/releases/tag/v1.2.0)
